services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=todolist-db'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRESS_ROOT_PASSWORD=root'
      - 'POSTGRES_PASSWORD=password'
    ports:
      - '5432:5432'
    expose:
      - '5432'
